export const ASSET_CONSTANT = {
  SVG: {
    LogoSingle: '/assets/svgs/common/logo-single.svg',
    LogoFullDark: '/assets/svgs/common/logo-full-dark.svg',
    LogoFullLight: '/assets/svgs/common/logo-full-light.svg',
    LogoSquare: '/assets/svgs/common/logo-square.svg',
    LegendBar: '/assets/svgs/common/legend-bar.svg',
    Text404: '/assets/svgs/common/404.svg',
    BottomGradient404: '/assets/svgs/common/404_bottom_gradient.svg',

    IconCaretDown: '/assets/svgs/16/ic-caret-down.svg',
    IconCaretUp: '/assets/svgs/16/ic-caret-up.svg',

    IconBoldCircleInformation: '/assets/svgs/24/ic-bold-circle-information.svg',
    IconBoldTrash: '/assets/svgs/24/ic-bold-trash.svg',
    IconArrowRight: '/assets/svgs/24/ic-arrow-right.svg',
    IconBoldBoxOpen1: '/assets/svgs/24/ic-bold-box-open-1.svg',
    IconBoldCamera1: '/assets/svgs/24/ic-bold-camera-1.svg',
    IconBoldCamera: '/assets/svgs/24/ic-bold-camera.svg',
    IconBoldCaution: '/assets/svgs/24/ic-bold-caution.svg',
    IconBoldCircleCheck: '/assets/svgs/24/ic-bold-circle-check.svg',
    IconBoldCircleCloseMultiply:
      '/assets/svgs/24/ic-bold-circle-close-multiply.svg',
    IconLinearCircleInformation:
      '/assets/svgs/24/ic-linear-circle-information.svg',
    IconBoldDashboard: '/assets/svgs/24/ic-bold-dashboard.svg',
    IconBoldHome3: '/assets/svgs/24/ic-bold-home-3.svg',
    IconBoldHr: '/assets/svgs/24/ic-bold-hr.svg',
    IconBoldSetting1: '/assets/svgs/24/ic-bold-settings-1.svg',
    IconBoldSetting2: '/assets/svgs/24/ic-bold-settings-2.svg',
    IconEye: '/assets/svgs/24/ic-eye.svg',
    IconLinearArrowDownRight: '/assets/svgs/24/ic-linear-arrow-down-right.svg',
    IconLinearArrowDown: '/assets/svgs/24/ic-linear-arrow-down.svg',
    IconLinearArrowUpRight: '/assets/svgs/24/ic-linear-arrow-up-right.svg',
    IconLinearArrowUp: '/assets/svgs/24/ic-linear-arrow-up.svg',
    IconLinearCalendar: '/assets/svgs/24/ic-linear-calendar.svg',
    IconLinearCaution: '/assets/svgs/24/ic-linear-caution.svg',
    IconLinearCheck: '/assets/svgs/24/ic-linear-check.svg',
    IconLinearCloseMultiply: '/assets/svgs/24/ic-linear-close-multiply.svg',
    IconLinearDownload: '/assets/svgs/24/ic-linear-download.svg',
    IconLinearEdit: '/assets/svgs/24/ic-linear-edit.svg',
    IconLinearExtend: '/assets/svgs/24/ic-linear-extend.svg',
    IconLinearHelp: '/assets/svgs/24/ic-linear-help.svg',
    IconLinearHome2: '/assets/svgs/24/ic-linear-home-2.svg',
    IconLinearHome3: '/assets/svgs/24/ic-linear-home-3.svg',
    IconLinearImport: '/assets/svgs/24/ic-linear-import.svg',
    IconLinearLogout: '/assets/svgs/24/ic-linear-logout.svg',
    IconLinearMail: '/assets/svgs/24/ic-linear-mail.svg',
    IconLinearPlus: '/assets/svgs/24/ic-linear-plus.svg',
    IconLinearSearch: '/assets/svgs/24/ic-linear-search.svg',
    IconLinearSettings2: '/assets/svgs/24/ic-linear-settings-2.svg',
    IconLinearSpin: '/assets/svgs/24/ic-linear-spin.svg',
    IconLinearTrash: '/assets/svgs/24/ic-linear-trash.svg',
    IconMoon: '/assets/svgs/24/ic-moon.svg',
    IconReports: '/assets/svgs/24/ic-reports.svg',
    IconSun: '/assets/svgs/24/ic-sun.svg',
    IconUnhide: '/assets/svgs/24/ic-unhide.svg',

    CheckboxCheck: '/assets/svgs/common/checkbox-check.svg',
    CheckboxUnCheck: '/assets/svgs/common/checkbox-uncheck.svg',
    IconNotifyWarning: '/assets/svgs/common/icon-notify-warning.svg',
    IconStepSuccess: '/assets/svgs/common/icon-step-success.svg',
    LogoFullWhite: '/assets/svgs/common/logo-full-white.svg',

    IconBoldCalendar: '/assets/svgs/24/ic-bold-calendar.svg',
    IconLineTimer: '/assets/svgs/24/ic-line-timer.svg',
    IconLogout: '/assets/svgs/24/ic-logout.svg',
    IconAvatar: '/assets/svgs/80/ic-avatar',
  },
  IMAGE: {
    AvatarEmpty: '/assets/images/avatar-empty.png',
    ImageEmpty: '/assets/images/image-empty.png',
    NotFindData: '/assets/images/not-find-data.png',
    NotFindMediaData: '/assets/images/not-find-media-data.png',
    NotFindVideo: '/assets/images/not-find-video.png',

    CameraAI: '/assets/images/login/camera-ai.jpeg',
    LoginOverlay2: '/assets/images/login/login-overlay-2.png',
    BackgroundLoginDark: '/assets/images/login/background-login-dark.png',
    BackgroundLoginLight: '/assets/images/login/background-login-light.png',
    Avatar1: '/assets/images/avatar/avatar1.png',
  },
};
