/**
 * Base API paths - Root level paths for different modules
 */
const BASE_PATHS = {
  USER_MANAGEMENT: '/user-management',
  GROUP_MANAGEMENT: '/group-management',
  PEOPLE_COUNTING: '/people-counting-management',
  USERS: '/users',
} as const;

const METRIC_PATHS = {
  PEOPLE_COUNTING: {
    BASE: BASE_PATHS.PEOPLE_COUNTING,
    REPORT: `${BASE_PATHS.PEOPLE_COUNTING}/report`,
    RETAIL: {
      BASE: `${BASE_PATHS.PEOPLE_COUNTING}/retail`,
      OVERVIEW_DATA: `${BASE_PATHS.PEOPLE_COUNTING}/retail/dashboard`,
      ANALYTICS: `${BASE_PATHS.PEOPLE_COUNTING}/retail/analystics`,
      GROUPS: `${BASE_PATHS.PEOPLE_COUNTING}/retail/groups`,
      CAMERAS: `${BASE_PATHS.PEOPLE_COUNTING}/retail/cameras`,
      ZONES: `${BASE_PATHS.PEOPLE_COUNTING}/retail/zones`,
      ROUTE_MAP: `${BASE_PATHS.PEOPLE_COUNTING}/retail/route-map`,
    },
  },
} as const;

export const AUTH_ENDPOINTS = {
  LOGIN: `${BASE_PATHS.USER_MANAGEMENT}/login`,
} as const;

export const USER_ENDPOINTS = {
  GET_PROFILE: `${BASE_PATHS.USER_MANAGEMENT}/get-profile`,
} as const;

export const GROUP_ENDPOINTS = {
  LIST: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.GROUPS}/all`,
} as const;

export const CAMERA_ENDPOINTS = {
  LIST: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.CAMERAS}/all`,
};

export const ZONE_ENDPOINTS = {
  LIST: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ZONES}/all`,
} as const;

export const DATA_OVERVIEW_ENDPOINTS = {
  DATA_OVERVIEW: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.OVERVIEW_DATA}/data-overview`,
  TRAFFIC_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.OVERVIEW_DATA}/traffic-chart`,
  ZONE_TRAFFIC_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.OVERVIEW_DATA}/zone-traffic-chart`,
  TRANSACTION_AND_INTERACTION_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.OVERVIEW_DATA}/transaction-and-interaction-chart`,
  EXPORT_TRAFFIC_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.OVERVIEW_DATA}/export/traffic-chart`,
} as const;

export const ANALYTICS_ENDPOINTS = {
  SUMMARY_TABLE: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/summary-table`,
  TOP_STORE: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/top-store`,
  STORE_COMPARISON: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/store-comparison`,
  ZONE_TRAFFIC_OVERVIEW: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/zone-traffic-overview`,
  ZONE_AND_TRAFFIC_OVERVIEW: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/zone-and-traffic-overview`,
  ZONE_AND_TRAFFIC_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/zone-and-traffic-chart`,
  TOTAL_ZONE_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/total-zone-chart`,
  ZONE_COMPARISON: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/zone-comparison`,
  STORE_TRANSACTION: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/store-transaction`,
  TRAFFIC_TREND_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/traffic-trend-chart`,
  EXPORT_VISITOR_TRAFFIC: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/export/visitor-traffic-trend`,
  EXPORT_STORE_COMPARISON: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/export/store-comparison`,
  EXPORT_TRANSACTION_AND_INTERACTION_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/export/transaction-and-interaction-chart`,
  EXPORT_ZONE_COMPARISON: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/export/zone-comparison`,
  EXPORT_ZONE_TRAFFIC_CHART: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ANALYTICS}/export/zone-traffic-chart`,
} as const;

export const ROUTE_MAP_ENDPOINTS = {
  ROUTE_MAP_DATA: `${METRIC_PATHS.PEOPLE_COUNTING.RETAIL.ROUTE_MAP}/by-camera?`,
} as const;
