import os

from dotenv import load_dotenv

load_dotenv()

ENV = os.getenv("ENV", default="DEV")
PORT = os.getenv("PORT", default="8000")

# SECRET KEY
SECRET_KEY = os.getenv("SECRET_KEY")
INTERNAL_SECRET_KEY = os.getenv("INTERNAL_SECRET_KEY")

# Minio
MINIO_HOST = os.getenv("MINIO_HOST")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_REGION = os.getenv("MINIO_REGION")
MINIO_NOTIFICATION_BUCKET = os.getenv("MINIO_NOTIFICATION_BUCKET")

# REDIS
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DATABASE = os.getenv("REDIS_DATABASE")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

# Firebase
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# MONGODB
MONGO_URI = os.getenv("MONGO_URI")
MONGODB_NAME = os.getenv("MONGODB_NAME")
# Mongo collections
# USER_COLLECTION = os.getenv("USER_COLLECTION")
NOTIFICATION_COLLECTION = os.getenv("NOTIFICATION_COLLECTION")
